# Var section let's you override some necessary variables
# All optionals
var:
# input: "sample.tex"
# comment_symbol: "%"
# -------------------------
# Chapters section let's you choose which part of the document will stay and which will be removed
chapters:
  experience: true
  education: true
# -------------------------
# Langs section is like the chapters' section but it will create a new document for each lang
langs:
  english: true
  french: true
